language: go
sudo: false

services:
  - postgresql

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - go get -u github.com/lib/pq
  - go get -u github.com/blendlabs/go-assert
  - go get -u github.com/blendlabs/go-exception

script: 
  - DB_SCHEMA=travis_ci_test go test